# Usage: kind create cluster --config ./hack/cluster_config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster-for-enet
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 30000
      hostPort: 9090
      protocol: TCP
    - containerPort: 30001
      hostPort: 9091
      protocol: TCP
    - containerPort: 30002
      hostPort: 9092
      protocol: TCP